version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./images:/etc/images
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      - PROJECT_NAME=Hackathon FastAPI Backend
      - VERSION=0.1.0