name: hackathon-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1.2
  - pip:
      - fastapi>=0.100.0
      - uvicorn[standard]>=0.22.0
      - sqlalchemy>=2.0.0
      - psycopg2-binary>=2.9.6
      - python-dotenv>=1.0.0
      - alembic>=1.11.1
      - pytest>=7.3.1
      - httpx>=0.24.1
      - uvicorn-watchfiles>=0.22.0  # For live reload functionality